global using FastEndpoints;
global using CleanArchitectureSampleProject.Core.Application.UseCases;
global using CleanArchitectureSampleProject.CrossCuttingConcerns;
global using CleanArchitectureSampleProject.Presentation.FastEndpoints.Configuration.Middlewares;
global using FluentValidation;
global using FluentValidation.Results;
global using System.Net;
global using static CleanArchitectureSampleProject.CrossCuttingConcerns.PolicyExtensions;