global using CleanArchitectureSampleProject.Core.Application.Inputs;
global using CleanArchitectureSampleProject.Core.Application.Outputs;
global using CleanArchitectureSampleProject.CrossCuttingConcerns;
global using Microsoft.Extensions.Logging;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel.DataAnnotations;
global using System.Linq;
global using System.Threading.Tasks;